# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam's Site
email: samlau95@gmail.com

logo: "/assets/images/lightbulb.png"
baseurl: "/" # the subpath of your site, e.g. /blog
imageurl: "/assets/images"

url: "http://samlau.me/" # the base hostname & protocol for your site

paginate:	5 # The number of posts to show per page on your homepage
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:categories/:title"

collections:
  current_projects:
    output: true
    permalink: /projects/:name
  past_projects:
    output: true
    permalink: /projects/:name

name: 'Sam'
bio: >
author_image: "/assets/images/sam.jpg"
github_username: samlau95

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

sass:
  style: compressed

ga_id: UA-42949369-4

