# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Lau
email: samlau95@gmail.com

logo: "/assets/images/lightbulb.png"
imageurl: "/assets/images"

paginate:	5 # The number of posts to show per page on your homepage
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:categories/:title"

collections:
  current_projects:
    output: true
    permalink: /projects/:name
  past_projects:
    output: true
    permalink: /projects/:name

name: 'Sam Lau'
description: >
  I'm Sam Lau! I'm a MS student at UC Berkeley advised by Josh Hug. I am
  interested in improving data science education. Currently, I'm building tools
  to make it easy to create and publish interactive educational content online.
author_image: "/assets/images/sam.jpg"
github_username: samlau95

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-github-metadata

sass:
  style: compressed

ga_id: UA-42949369-4

